name: Pages
on:
  push:
  schedule:
    - cron: '0 3 * * 0' # Runs every Sunday at 3am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Setup hq
        run: |
          curl -sL https://github.com/ludovicianul/hq/releases/download/hq-1.3.2/hq_linux_amd64_1.3.2.tar.gz --output - | tar -xzv
      - run: |
          export HQ=$(realpath ./hq)
          make
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: _site

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: Github Pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
